/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Warstwa_klienta;

import Warstwa_Biznesowa.EgzemplarzSamochodu;
import Warstwa_Biznesowa.Fasada;
import Warstwa_Biznesowa.Klient;
import Warstwa_Biznesowa.ModelSamochodu;
import Warstwa_Biznesowa.Rezerwacja;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Falco
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form MainGUI
     */
    public MainGUI() {
        initComponents();
        fasada = new Fasada();
        fillTableModeleSamochodow();
        fillTableModeleDodajEgzemplarz();
        fillTableEgzemplarzeModeli();
        fillTableKlienci();
    }
    Fasada fasada;
    ArrayList<Klient> wybraniKlienci;
    ArrayList<EgzemplarzSamochodu> wybraneEgzemplarze;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jTabbedPaneRezerwacje = new javax.swing.JTabbedPane();
        jPanelModeleSamochodow = new javax.swing.JPanel();
        jTextFieldMarka = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldModel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jButtonDodajModel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModeleSamochodow = new javax.swing.JTable();
        jPanelEgzemplarzeSamochodow = new javax.swing.JPanel();
        jButtonDodajEgzemplarz = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRejstracja = new javax.swing.JTextField();
        jSpinnerRok = new javax.swing.JSpinner();
        jComboBoxPaliwo = new javax.swing.JComboBox();
        jComboBoxNadwozie = new javax.swing.JComboBox();
        jSpinnerSilnik = new javax.swing.JSpinner();
        jScrollPane11 = new javax.swing.JScrollPane();
        jTableModeleDodajEgzemplarz = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEgzemplarzeModeli = new javax.swing.JTable();
        jPanelKlienci = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldImie = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldNazwisko = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPesel = new javax.swing.JTextField();
        jButtonDodajKlienta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableKlienci = new javax.swing.JTable();
        jPanelRezerwacje = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableKlienciR1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSzukaj = new javax.swing.JTextField();
        jButtonSzukaj = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldEgzemplarz = new javax.swing.JTextField();
        jButtonSzukajEgzemplarza = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableWolneEgzemplarze = new javax.swing.JTable();
        jSpinnerWypozyczenie = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jSpinnerIloscDni = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        jButtonZarezerwuj = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTableRezerwacjeKlienta = new javax.swing.JTable();
        jPanelRezerwacjeR2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldKlientR2 = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableKlienciR2 = new javax.swing.JTable();
        jButtonSzukajR2 = new javax.swing.JButton();
        jTextFieldModelSamochoduR2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jButtonSzukajModeluR2 = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTableModeleR2 = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jTableEgzemplarzeR2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jTextFieldEgzemplarzR2 = new javax.swing.JTextField();
        jSpinnerDataR2 = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSpinnerIloscDniR2 = new javax.swing.JSpinner();
        jButtonSzukajEgzemplarzyR2Wzorzec = new javax.swing.JButton();
        jButtonSzukajEgzemplarzyR2Model = new javax.swing.JButton();
        jButtonRezerwujR2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTableRezerwacjeR2 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel19.setText("jLabel19");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Podaj Markę:");

        jLabel2.setText("Podaj Model:");

        jLabel3.setText("Podaj ilość miejsc:");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(5, 1, 120, 1));

        jButtonDodajModel.setText("Dodaj Model");
        jButtonDodajModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajModelActionPerformed(evt);
            }
        });

        jTableModeleSamochodow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableModeleSamochodow);

        javax.swing.GroupLayout jPanelModeleSamochodowLayout = new javax.swing.GroupLayout(jPanelModeleSamochodow);
        jPanelModeleSamochodow.setLayout(jPanelModeleSamochodowLayout);
        jPanelModeleSamochodowLayout.setHorizontalGroup(
            jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldModel))
                    .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner1))
                    .addComponent(jButtonDodajModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelModeleSamochodowLayout.setVerticalGroup(
            jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelModeleSamochodowLayout.createSequentialGroup()
                        .addGroup(jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelModeleSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDodajModel)
                        .addGap(0, 485, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        jTabbedPaneRezerwacje.addTab("Modele Samochodów", jPanelModeleSamochodow);

        jButtonDodajEgzemplarz.setText("Dodaj Egzemplarz");
        jButtonDodajEgzemplarz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajEgzemplarzActionPerformed(evt);
            }
        });

        jLabel5.setText("Nr rejstracyjny:");

        jLabel6.setText("Rok produkcji:");

        jLabel7.setText("Rodzaj paliwa:");

        jLabel8.setText("Typ nadwozia:");

        jLabel9.setText("Pojemnosc silnika:");

        jSpinnerRok.setModel(new javax.swing.SpinnerNumberModel(2010, 1900, 2999, 1));

        jComboBoxPaliwo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Benzyna", "Diesel", "Benzyna + LPG", "Hybryda", "Elektryczny" }));

        jComboBoxNadwozie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cabriolet", "Sedan", "Kombi", "Limuzyna", "Hachbak", "Ciężarowy" }));

        jSpinnerSilnik.setModel(new javax.swing.SpinnerNumberModel(1598, 0, 20000, 1));

        jTableModeleDodajEgzemplarz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTableModeleDodajEgzemplarz.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTableModeleDodajEgzemplarzPropertyChange(evt);
            }
        });
        jScrollPane11.setViewportView(jTableModeleDodajEgzemplarz);

        jTableEgzemplarzeModeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableEgzemplarzeModeli);

        javax.swing.GroupLayout jPanelEgzemplarzeSamochodowLayout = new javax.swing.GroupLayout(jPanelEgzemplarzeSamochodow);
        jPanelEgzemplarzeSamochodow.setLayout(jPanelEgzemplarzeSamochodowLayout);
        jPanelEgzemplarzeSamochodowLayout.setHorizontalGroup(
            jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEgzemplarzeSamochodowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEgzemplarzeSamochodowLayout.createSequentialGroup()
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldRejstracja, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(jSpinnerRok)))
                    .addComponent(jButtonDodajEgzemplarz, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelEgzemplarzeSamochodowLayout.createSequentialGroup()
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(52, 52, 52)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerSilnik)
                            .addComponent(jComboBoxPaliwo, 0, 137, Short.MAX_VALUE)
                            .addComponent(jComboBoxNadwozie, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelEgzemplarzeSamochodowLayout.setVerticalGroup(
            jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEgzemplarzeSamochodowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanelEgzemplarzeSamochodowLayout.createSequentialGroup()
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldRejstracja, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jSpinnerRok, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxPaliwo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jComboBoxNadwozie, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelEgzemplarzeSamochodowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jSpinnerSilnik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDodajEgzemplarz)))
                .addContainerGap())
        );

        jTabbedPaneRezerwacje.addTab("Egzemplarze Samochodów", jPanelEgzemplarzeSamochodow);

        jLabel4.setText("Imię:");

        jLabel10.setText("Nazwisko:");

        jLabel11.setText("PESEL:");

        jButtonDodajKlienta.setText("Dodaj Klienta");
        jButtonDodajKlienta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajKlientaActionPerformed(evt);
            }
        });

        jTableKlienci.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableKlienci);

        javax.swing.GroupLayout jPanelKlienciLayout = new javax.swing.GroupLayout(jPanelKlienci);
        jPanelKlienci.setLayout(jPanelKlienciLayout);
        jPanelKlienciLayout.setHorizontalGroup(
            jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKlienciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKlienciLayout.createSequentialGroup()
                        .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(40, 40, 40)
                        .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldImie, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                                .addComponent(jTextFieldNazwisko))
                            .addComponent(jTextFieldPesel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonDodajKlienta, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelKlienciLayout.setVerticalGroup(
            jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKlienciLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKlienciLayout.createSequentialGroup()
                        .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextFieldImie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelKlienciLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldPesel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDodajKlienta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPaneRezerwacje.addTab("Klienci", jPanelKlienci);

        jTableKlienciR1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(jTableKlienciR1);

        jLabel12.setText("Klient:");

        jButtonSzukaj.setText("Szukaj Klienta");
        jButtonSzukaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajActionPerformed(evt);
            }
        });

        jLabel13.setText("Egzemplarz:");

        jButtonSzukajEgzemplarza.setText("Szukaj Egzemplarza");
        jButtonSzukajEgzemplarza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajEgzemplarzaActionPerformed(evt);
            }
        });

        jTableWolneEgzemplarze.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane6.setViewportView(jTableWolneEgzemplarze);

        jSpinnerWypozyczenie.setModel(new javax.swing.SpinnerDateModel());

        jLabel14.setText("Wypożyczenie:");

        jSpinnerIloscDni.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));

        jLabel17.setText("Ilość dni:");

        jButtonZarezerwuj.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonZarezerwuj.setText("Zarezerwuj");
        jButtonZarezerwuj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZarezerwujActionPerformed(evt);
            }
        });

        jTableRezerwacjeKlienta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane7.setViewportView(jTableRezerwacjeKlienta);

        javax.swing.GroupLayout jPanelRezerwacjeLayout = new javax.swing.GroupLayout(jPanelRezerwacje);
        jPanelRezerwacje.setLayout(jPanelRezerwacjeLayout);
        jPanelRezerwacjeLayout.setHorizontalGroup(
            jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRezerwacjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonZarezerwuj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRezerwacjeLayout.createSequentialGroup()
                        .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelRezerwacjeLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSzukaj))
                            .addComponent(jButtonSzukaj, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                            .addGroup(jPanelRezerwacjeLayout.createSequentialGroup()
                                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRezerwacjeLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanelRezerwacjeLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(34, 34, 34)))
                                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerIloscDni, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerWypozyczenie, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRezerwacjeLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldEgzemplarz))
                                    .addComponent(jButtonSzukajEgzemplarza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jScrollPane7))
                .addContainerGap())
        );
        jPanelRezerwacjeLayout.setVerticalGroup(
            jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRezerwacjeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldSzukaj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerWypozyczenie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldEgzemplarz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSzukaj)
                    .addComponent(jButtonSzukajEgzemplarza)
                    .addComponent(jSpinnerIloscDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRezerwacjeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonZarezerwuj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPaneRezerwacje.addTab("Dodaj Rezerwacje (zle)", jPanelRezerwacje);

        jLabel15.setText("Klient:");

        jTableKlienciR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane8.setViewportView(jTableKlienciR2);

        jButtonSzukajR2.setText("Szukaj");
        jButtonSzukajR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajR2ActionPerformed(evt);
            }
        });

        jLabel16.setText("Model Samochodu:");

        jButtonSzukajModeluR2.setText("Szukaj");
        jButtonSzukajModeluR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajModeluR2ActionPerformed(evt);
            }
        });

        jTableModeleR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane9.setViewportView(jTableModeleR2);

        jTableEgzemplarzeR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane10.setViewportView(jTableEgzemplarzeR2);

        jLabel18.setText("Egzemplarz:");

        jSpinnerDataR2.setModel(new javax.swing.SpinnerDateModel());

        jLabel20.setText("Wypożyczenie:");

        jLabel21.setText("Ilość dni:");

        jSpinnerIloscDniR2.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));

        jButtonSzukajEgzemplarzyR2Wzorzec.setText("Szukaj wszystkich wolnych według wzorca");
        jButtonSzukajEgzemplarzyR2Wzorzec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajEgzemplarzyR2WzorzecActionPerformed(evt);
            }
        });

        jButtonSzukajEgzemplarzyR2Model.setText("Szukaj wolnych egzemplarzy wybranego modelu");
        jButtonSzukajEgzemplarzyR2Model.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSzukajEgzemplarzyR2ModelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldEgzemplarzR2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerIloscDniR2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerDataR2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSzukajEgzemplarzyR2Wzorzec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSzukajEgzemplarzyR2Model, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEgzemplarzR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jButtonSzukajEgzemplarzyR2Wzorzec))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jSpinnerDataR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jSpinnerIloscDniR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSzukajEgzemplarzyR2Model))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonRezerwujR2.setText("Utwórz rezerwację");
        jButtonRezerwujR2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRezerwujR2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRezerwacjeR2Layout = new javax.swing.GroupLayout(jPanelRezerwacjeR2);
        jPanelRezerwacjeR2.setLayout(jPanelRezerwacjeR2Layout);
        jPanelRezerwacjeR2Layout.setHorizontalGroup(
            jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRezerwacjeR2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelRezerwacjeR2Layout.createSequentialGroup()
                        .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelRezerwacjeR2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldKlientR2))
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                            .addComponent(jButtonSzukajR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSzukajModeluR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelRezerwacjeR2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldModelSamochoduR2))
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)))
                    .addComponent(jScrollPane10)
                    .addComponent(jButtonRezerwujR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
        jPanelRezerwacjeR2Layout.setVerticalGroup(
            jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRezerwacjeR2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldKlientR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldModelSamochoduR2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSzukajR2)
                    .addComponent(jButtonSzukajModeluR2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRezerwacjeR2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRezerwujR2)
                .addContainerGap())
        );

        jTabbedPaneRezerwacje.addTab("Dodaj Rezerwacje R2", jPanelRezerwacjeR2);

        jTableRezerwacjeR2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane12.setViewportView(jTableRezerwacjeR2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 897, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)
        );

        jTabbedPaneRezerwacje.addTab("Przeglądaj Rezerwacje R2", jPanel3);

        jMenu1.setText("Plik");

        jMenuItem1.setText("Utwórz dane DEMO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneRezerwacje)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPaneRezerwacje)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonDodajModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajModelActionPerformed
        if (jTextFieldModel.getText().equals("") || jTextFieldMarka.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Prosze podać dane");
            return;
        }
        String data[] = {jTextFieldMarka.getText(), jTextFieldModel.getText(),jSpinner1.getValue().toString()};
        boolean addModelSamochoduResult = fasada.addModelSamochodu(data);
        if(addModelSamochoduResult)
        {
            fillTableModeleSamochodow();
            fillTableModeleDodajEgzemplarz();
            JOptionPane.showMessageDialog(this, "Dodawanie modelu zakońćzone sukcesem.");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nie udało się dodać modelu. Sprawdż czy w systemie nie istnieje identyczny model.");
        }
    }//GEN-LAST:event_jButtonDodajModelActionPerformed

    private void jButtonDodajEgzemplarzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajEgzemplarzActionPerformed
        if (jTableModeleDodajEgzemplarz.getSelectionModel().isSelectionEmpty())
        {
            JOptionPane.showMessageDialog(this, "Prosze wybrać model");
            return;
        }
        if (jTextFieldRejstracja.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "Prosze podać nr rejstracyjny");
            return;
        }
        String model = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 0).toString();
        String marka = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 1).toString();
        String miejsca = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 2).toString();
        
        String dataModel[] = {model,marka,miejsca};
        String dataEgzemplarz[] = {jTextFieldRejstracja.getText(), jSpinnerRok.getValue().toString(),
            jComboBoxPaliwo.getSelectedItem().toString(), jComboBoxNadwozie.getSelectedItem().toString(), jSpinnerSilnik.getValue().toString()};

        if(fasada.add_EgzemplarzSamochodu(dataModel, dataEgzemplarz) != null)
        {
            JOptionPane.showMessageDialog(this, "Dodawanie egzemplarzu zakońćzone sukcesem.");
            fillTableEgzemplarzeModeli();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nie udało się dodać egzemplarza. Sprawdź czy w systemie nie istnieje identyczny egzemplarz.");
        }
    }//GEN-LAST:event_jButtonDodajEgzemplarzActionPerformed

    private void jButtonDodajKlientaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajKlientaActionPerformed
        String[] daneKlienta = {jTextFieldImie.getText(),jTextFieldNazwisko.getText(),jTextFieldPesel.getText()};
        if (daneKlienta[0].equals("") || daneKlienta[1].equals("") || daneKlienta[2].equals(""))
        {
            JOptionPane.showMessageDialog(this, "Prosze podać Imię, Nazwisko oraz PESEL dane");
            return;
        }
        try
        {
            Integer.parseInt(jTextFieldPesel.getText());
        }
        catch(NumberFormatException e)
        {   
            JOptionPane.showMessageDialog(this, "W polu 'PESEL' wymagany format liczbowy");
            return;
        }
        boolean result = fasada.addKlient(daneKlienta);
        if(result)
        {
            fillTableKlienci();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Nie udało się dodać klienta. Sprawdź, czy taki sam klient nie istnieje.");
        }
    }//GEN-LAST:event_jButtonDodajKlientaActionPerformed

    private void jButtonSzukajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajActionPerformed
        wybraniKlienci = fasada.szukajKlienta(jTextFieldSzukaj.getText());
        fillTableKlienci(wybraniKlienci);
    }//GEN-LAST:event_jButtonSzukajActionPerformed

    private void jButtonZarezerwujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZarezerwujActionPerformed
        Klient klient = wybraniKlienci.get(jTableKlienciR1.getSelectedRow());
        EgzemplarzSamochodu egzemplarz = wybraneEgzemplarze.get(jTableWolneEgzemplarze.getSelectedRow());
        Date wypozyczenie = (Date)jSpinnerWypozyczenie.getValue();
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(wypozyczenie);
        cal.add(Calendar.DATE, (int)jSpinnerIloscDni.getValue());
        cal.getTime();
        Date zwrot = cal.getTime();
        if(!fasada.addRezerwacja(klient, egzemplarz, wypozyczenie, zwrot)){
            JOptionPane.showMessageDialog(this, "Nie udało się dodać rezerwacji. Sprawdź, czy taka razerwacja już nie istnieje.");
        }
        fillTableRezerwacjeKlienta();
    }//GEN-LAST:event_jButtonZarezerwujActionPerformed

    private void jButtonSzukajEgzemplarzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajEgzemplarzaActionPerformed
        Date wypozyczenie = (Date)jSpinnerWypozyczenie.getValue();
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(wypozyczenie);
        cal.add(Calendar.DATE, (int)jSpinnerIloscDni.getValue());
        cal.getTime();
        Date zwrot = cal.getTime();
        wybraneEgzemplarze = fasada.szukajEgzemplarza(jTextFieldEgzemplarz.getText(), wypozyczenie, zwrot);
    }//GEN-LAST:event_jButtonSzukajEgzemplarzaActionPerformed

    private void jButtonSzukajR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajR2ActionPerformed
        fillTableKlienciR2(fasada.szukajKlientaR2(jTextFieldKlientR2.getText()));
        
    }//GEN-LAST:event_jButtonSzukajR2ActionPerformed

    private void jButtonSzukajModeluR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajModeluR2ActionPerformed
        fillTableModeleR2(fasada.szukajModeluR2(jTextFieldModelSamochoduR2.getText()));
    }//GEN-LAST:event_jButtonSzukajModeluR2ActionPerformed

    private void jButtonSzukajEgzemplarzyR2WzorzecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajEgzemplarzyR2WzorzecActionPerformed
        Date wypozyczenie = (Date)jSpinnerDataR2.getValue();
        GregorianCalendar cal = new GregorianCalendar();
        cal.setTime(wypozyczenie);
        cal.add(Calendar.DATE, (int)jSpinnerIloscDniR2.getValue());
        cal.getTime();
        Date zwrot = cal.getTime();
        fillTableEgzemplarzeR2(fasada.szukajEgzemplarzaR2Wzorzec(jTextFieldEgzemplarzR2.getText(), wypozyczenie.getTime(), zwrot.getTime()));
    }//GEN-LAST:event_jButtonSzukajEgzemplarzyR2WzorzecActionPerformed

    private void jButtonSzukajEgzemplarzyR2ModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSzukajEgzemplarzyR2ModelActionPerformed
        if(jTableModeleR2.getSelectedRow() != -1)
        {
            String model = jTableModeleR2.getModel().getValueAt(jTableModeleR2.getSelectedRow(), 0).toString();
            String marka = jTableModeleR2.getModel().getValueAt(jTableModeleR2.getSelectedRow(), 1).toString();
            String miejsca = jTableModeleR2.getModel().getValueAt(jTableModeleR2.getSelectedRow(), 2).toString();
            String[] modelSamochodu = {model, marka, miejsca};
            Date wypozyczenie = (Date)jSpinnerDataR2.getValue();
            GregorianCalendar cal = new GregorianCalendar();
            cal.setTime(wypozyczenie);
            cal.add(Calendar.DATE, (int)jSpinnerIloscDniR2.getValue());
            cal.getTime();
            Date zwrot = cal.getTime();
            fillTableEgzemplarzeR2(fasada.szukajEgzemplarzaR2Model(modelSamochodu, jTextFieldEgzemplarzR2.getText(), wypozyczenie.getTime(), zwrot.getTime()));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Proszę najpierw wybrać model samochodu.");
        }
    }//GEN-LAST:event_jButtonSzukajEgzemplarzyR2ModelActionPerformed

    private void jButtonRezerwujR2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRezerwujR2ActionPerformed
        if(jTableKlienciR2.getSelectedRow() != -1 && jTableEgzemplarzeR2.getSelectedRow() != -1)
        {
            String imie = jTableKlienciR2.getModel().getValueAt(jTableKlienciR2.getSelectedRow(), 0).toString();
            String nazwisko = jTableKlienciR2.getModel().getValueAt(jTableKlienciR2.getSelectedRow(), 1).toString();
            String pesel = jTableKlienciR2.getModel().getValueAt(jTableKlienciR2.getSelectedRow(), 2).toString();
            String[] klient = {imie,nazwisko,pesel};
            
            String marka = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 0).toString();
            String model = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 1).toString();
            String miejsca = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 2).toString();
            String rejstracja = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 3).toString();
            String paliwo = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 4).toString();
            String rocznik = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 5).toString();
            String nadwozie = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 6).toString();
            String pojemnosc = jTableEgzemplarzeR2.getModel().getValueAt(jTableEgzemplarzeR2.getSelectedRow(), 7).toString();
            String[] egzemplarz = {marka,model,miejsca,rejstracja,paliwo,rocznik,nadwozie,pojemnosc};
            
            Date wypozyczenie = (Date)jSpinnerDataR2.getValue();
            GregorianCalendar cal = new GregorianCalendar();
            cal.setTime(wypozyczenie);
            cal.add(Calendar.DATE, (int)jSpinnerIloscDniR2.getValue());
            cal.getTime();
            Date zwrot = cal.getTime();
            
            boolean result = fasada.addRezerwacja(klient, egzemplarz, wypozyczenie.getTime(), zwrot.getTime());
            
            if(result)
            {
                fillTableRezerwacje();
                JOptionPane.showMessageDialog(this, "Rezerwacja utworzona pomyślnie.");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Nie udało się utworzyć rezerwacji. Sprawdź, czy taka sama rezerwacja już nie istnieje.");
            }
            
        }
        else{
            JOptionPane.showMessageDialog(this, "Prosze wybrac klienta oraz egzemplarz samochodu.");
        }
    }//GEN-LAST:event_jButtonRezerwujR2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String[] data = {"Opel","Astra G","5"};
        String[] data1 = {"Fiat","126p","4"};
        String[] data2 = {"Ford","Fiesta","5"};
        
        fasada.addModelSamochodu(data);
        fasada.addModelSamochodu(data1);
        fasada.addModelSamochodu(data2);
        
        String[] data1e = {"DL82852","2000","Benzyna","Kombi","1598"};
        String[] data2e = {"DW54323","2001","Diesel","Sedan","1998"};
        String[] data3e = {"DW54323","2005","Diesel","Sedan","995"};

        fasada.add_EgzemplarzSamochodu(data, data1e);
        fasada.add_EgzemplarzSamochodu(data, data2e);
        fasada.add_EgzemplarzSamochodu(data1, data2e);
        fasada.add_EgzemplarzSamochodu(data1, data3e);
        
        String[] klient1 = {"Michal","Lange","86090900358"};
        String[] klient2 = {"Janusz","Jakistam","88121112413"};
        
        fasada.addKlient(klient1);
        fasada.addKlient(klient2);
        
        fillTableModeleSamochodow();
        fillTableModeleDodajEgzemplarz();
        fillTableKlienci();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jTableModeleDodajEgzemplarzPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTableModeleDodajEgzemplarzPropertyChange
        fillTableEgzemplarzeModeli();
    }//GEN-LAST:event_jTableModeleDodajEgzemplarzPropertyChange
    
    private void fillTableRezerwacje() {
        String col[] = {"Rezerwacje" };
        DefaultTableModel defaultTableModelRezerwacja = new DefaultTableModel(col,0);
        jTableRezerwacjeR2.setModel(defaultTableModelRezerwacja);
        for(String[] rezerwacja: fasada.getWszystkieRezerwacje())
        {
            Object[] objs = {rezerwacja[0]};
            defaultTableModelRezerwacja.addRow(objs);
        }
        
    }
    
    private void fillTableEgzemplarzeR2(String[][] egzemplarze){
            String col[] = {"Model","Marka","Miejsca","Rejstracja","Paliwo","Rocznik","Nadwozie","Pojemnosc" };
            DefaultTableModel defaultTableModelModeleEgzemplarz = new DefaultTableModel(col,0);
            jTableEgzemplarzeR2.setModel(defaultTableModelModeleEgzemplarz);
            for (String egzemplarz[] : egzemplarze) {
                Object[] objs = {egzemplarz[0],egzemplarz[1],egzemplarz[2],egzemplarz[3],egzemplarz[4],egzemplarz[5],egzemplarz[6],egzemplarz[7]};
                defaultTableModelModeleEgzemplarz.addRow(objs);
            }
    }
    
    private void fillTableModeleR2(String[][] modele){
            String col[] = {"Marka","Model","Ilosc Miejsc"};
            DefaultTableModel defaultTableModelModel = new DefaultTableModel(col,0);
            jTableModeleR2.setModel(defaultTableModelModel);
            for (String model[] : modele) {
                Object[] objs = {model[0], model[1], model[2]};
                defaultTableModelModel.addRow(objs);
            }
    }
    
    private void fillTableKlienciR2(String[][] klienci){
            String col[] = {"Imię","Nazwisko","Pesel"};
            DefaultTableModel defaultTableModelModeleKlienci = new DefaultTableModel(col,0);
            jTableKlienciR2.setModel(defaultTableModelModeleKlienci);
            for (String klient[] : klienci) {
                Object[] objs = {klient[0], klient[1], klient[2]};
                defaultTableModelModeleKlienci.addRow(objs);
            }
    }
    
    private void fillTableRezerwacjeKlienta()
    {
            String col[] = {"Wypozyczenie","Zwrot","Marka","Model"};
            DefaultTableModel defaultTableModelRezerwacjeKlienta = new DefaultTableModel(col,0);
            jTableRezerwacjeKlienta.setModel(defaultTableModelRezerwacjeKlienta);
            Klient klient = wybraniKlienci.get(jTableKlienciR1.getSelectedRow());
            for(Rezerwacja rezerwacjaKlienta: klient.getRezerwacjeKlienta())
            {
                Object[] objs = {rezerwacjaKlienta.getCzasWypozyczenia().toString(),
                                rezerwacjaKlienta.getCzasZwrotu().toString(),
                                rezerwacjaKlienta.getModelSamochodu().getMarka(),
                                rezerwacjaKlienta.getModelSamochodu().getModel()};
                defaultTableModelRezerwacjeKlienta.addRow(objs);
            }
            
    }
    
    private void fillTableKlienci(){
        
        String col[] = {"Imię","Nazwisko","Pesel"};
        DefaultTableModel defaultTableModelModeleKlienci = new DefaultTableModel(col,0);
        jTableKlienci.setModel(defaultTableModelModeleKlienci);
        for (String klient[] : fasada.getKlienciAsStringArray()) {
            Object[] objs = {klient[0], klient[1], klient[2]};
            defaultTableModelModeleKlienci.addRow(objs);
        }
    }

    private void fillTableKlienci(ArrayList<Klient> klienci){
            String col[] = {"Imię","Nazwisko","Pesel"};
            DefaultTableModel defaultTableModelModeleKlienci = new DefaultTableModel(col,0);
            jTableKlienciR1.setModel(defaultTableModelModeleKlienci);
            for (Klient klient : klienci) {
                Object[] objs = {klient.getImie(),klient.getNazwisko(),klient.getPesel()};
                defaultTableModelModeleKlienci.addRow(objs);
            }
    }
    
    private void fillTableModeleSamochodow(){
            String col[] = {"Marka","Model","Ilosc Miejsc"};
            DefaultTableModel defaultTableModelModeleSamochodow = new DefaultTableModel(col,0);
            jTableModeleSamochodow.setModel(defaultTableModelModeleSamochodow);
            for (String[] model: fasada.getModeleSamochoduAsStringArray()) {
                Object[] objs = {model[0],model[1],model[2]};
                defaultTableModelModeleSamochodow.addRow(objs);
            }
    }
    
    private void fillTableModeleDodajEgzemplarz() {
        String col[] = {"Marka","Model","Ilosc Miejsc"};
            DefaultTableModel defaultTableModelModeleSamochodow = new DefaultTableModel(col,0);
            jTableModeleDodajEgzemplarz.setModel(defaultTableModelModeleSamochodow);
            for (String[] model: fasada.getModeleSamochoduAsStringArray()) {
                Object[] objs = {model[0],model[1],model[2]};
                defaultTableModelModeleSamochodow.addRow(objs);
            }
    }

    private void fillTableEgzemplarzeModeli(){
        if (!jTableModeleDodajEgzemplarz.getSelectionModel().isSelectionEmpty())
        {
            String col[] = {"Marka","Model","Miejsca","Rejstracja","Paliwo","Rocznik","Nadwozie","Pojemnosc" };
            DefaultTableModel defaultTableModelEgzemplarzeModeli = new DefaultTableModel(col,0);
            jTableEgzemplarzeModeli.setModel(defaultTableModelEgzemplarzeModeli);
            String marka = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 0).toString();
            String model = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 1).toString();
            String miejsca = jTableModeleDodajEgzemplarz.getModel().getValueAt(jTableModeleDodajEgzemplarz.getSelectedRow(), 2).toString();
            String dataModel[] = {model,marka,miejsca};
            String egzemplarzeModelu[][] = fasada.getEgzemplarzeModeluAsStringArray(dataModel);
            for (String egzemplarz[] : egzemplarzeModelu) {
                Object[] objs = {egzemplarz[0],egzemplarz[1],egzemplarz[2],egzemplarz[3],egzemplarz[4],egzemplarz[5],egzemplarz[6],egzemplarz[7]};
                defaultTableModelEgzemplarzeModeli.addRow(objs);
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajEgzemplarz;
    private javax.swing.JButton jButtonDodajKlienta;
    private javax.swing.JButton jButtonDodajModel;
    private javax.swing.JButton jButtonRezerwujR2;
    private javax.swing.JButton jButtonSzukaj;
    private javax.swing.JButton jButtonSzukajEgzemplarza;
    private javax.swing.JButton jButtonSzukajEgzemplarzyR2Model;
    private javax.swing.JButton jButtonSzukajEgzemplarzyR2Wzorzec;
    private javax.swing.JButton jButtonSzukajModeluR2;
    private javax.swing.JButton jButtonSzukajR2;
    private javax.swing.JButton jButtonZarezerwuj;
    private javax.swing.JComboBox jComboBoxNadwozie;
    private javax.swing.JComboBox jComboBoxPaliwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEgzemplarzeSamochodow;
    private javax.swing.JPanel jPanelKlienci;
    private javax.swing.JPanel jPanelModeleSamochodow;
    private javax.swing.JPanel jPanelRezerwacje;
    private javax.swing.JPanel jPanelRezerwacjeR2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerDataR2;
    private javax.swing.JSpinner jSpinnerIloscDni;
    private javax.swing.JSpinner jSpinnerIloscDniR2;
    private javax.swing.JSpinner jSpinnerRok;
    private javax.swing.JSpinner jSpinnerSilnik;
    private javax.swing.JSpinner jSpinnerWypozyczenie;
    private javax.swing.JTabbedPane jTabbedPaneRezerwacje;
    private javax.swing.JTable jTableEgzemplarzeModeli;
    private javax.swing.JTable jTableEgzemplarzeR2;
    private javax.swing.JTable jTableKlienci;
    private javax.swing.JTable jTableKlienciR1;
    private javax.swing.JTable jTableKlienciR2;
    private javax.swing.JTable jTableModeleDodajEgzemplarz;
    private javax.swing.JTable jTableModeleR2;
    private javax.swing.JTable jTableModeleSamochodow;
    private javax.swing.JTable jTableRezerwacjeKlienta;
    private javax.swing.JTable jTableRezerwacjeR2;
    private javax.swing.JTable jTableWolneEgzemplarze;
    private javax.swing.JTextField jTextFieldEgzemplarz;
    private javax.swing.JTextField jTextFieldEgzemplarzR2;
    private javax.swing.JTextField jTextFieldImie;
    private javax.swing.JTextField jTextFieldKlientR2;
    private javax.swing.JTextField jTextFieldMarka;
    private javax.swing.JTextField jTextFieldModel;
    private javax.swing.JTextField jTextFieldModelSamochoduR2;
    private javax.swing.JTextField jTextFieldNazwisko;
    private javax.swing.JTextField jTextFieldPesel;
    private javax.swing.JTextField jTextFieldRejstracja;
    private javax.swing.JTextField jTextFieldSzukaj;
    // End of variables declaration//GEN-END:variables

}
